from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, status
from motor.motor_asyncio import AsyncIOMotorDatabase
from bson import ObjectId

from app.api.deps import get_current_user, get_database
from ml.emotion_analysis import analyse_frame
from ml.speech_analysis import analyse_audio

router = APIRouter(prefix="/analysis", tags=["analysis"])


@router.post("/emotion-frame")
async def analyse_emotion_frame(
    interview_id: str,
    question_id: str,
    frame: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database),
):
    """Accept a single JPEG/PNG video frame and return emotion scores."""
    contents = await frame.read()
    scores = analyse_frame(contents)

    await db["interviews"].update_one(
        {"_id": ObjectId(interview_id), "questions_answers.question_id": question_id},
        {"$set": {"questions_answers.$.emotion_scores": scores}},
    )
    return {"emotion_scores": scores}


@router.post("/speech-metrics")
async def analyse_speech_metrics(
    interview_id: str,
    question_id: str,
    audio: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database),
):
    """Accept a WAV audio clip and return speech quality metrics."""
    contents = await audio.read()
    metrics = analyse_audio(contents)

    await db["interviews"].update_one(
        {"_id": ObjectId(interview_id), "questions_answers.question_id": question_id},
        {"$set": {"questions_answers.$.speech_metrics": metrics}},
    )
    return {"speech_metrics": metrics}


@router.get("/{interview_id}/report")
async def get_analysis_report(
    interview_id: str,
    current_user: dict = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database),
):
    """
    Return the full multimodal Report Card for a completed interview.
    The Phase 3C WebSocket engine saves a rich report_card dict to MongoDB
    (overall_score, visual_confidence_score, emotion_summary, visual_insight,
    strengths, improvements, per_question, etc.).  We return that directly.
    """
    doc = await db["interviews"].find_one({"_id": ObjectId(interview_id)})
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Interview not found.")

    report_card = doc.get("report_card")

    # ── Phase 3C report card (generated by the WebSocket engine) ──────────
    if report_card:
        return {
            "interview_id":    interview_id,
            "job_role":        doc.get("job_role"),
            "interview_type":  doc.get("interview_type"),
            "candidate_name":  doc.get("candidate_name"),
            "emotion_stats":   doc.get("emotion_stats", {}),
            **report_card,
        }

    # ── Fallback: session completed via the old HTTP /complete endpoint ───
    # Build a minimal response from per-question data so the ReportPage
    # still renders something useful for legacy sessions.
    qas = doc.get("questions_answers", [])
    return {
        "interview_id":          interview_id,
        "job_role":              doc.get("job_role"),
        "candidate_name":        doc.get("candidate_name"),
        "overall_score":         doc.get("overall_score"),
        "communication_score":   None,
        "technical_score":       None,
        "confidence_score":      None,
        "visual_confidence_score": None,
        "verdict":               "Maybe",
        "summary":               "This session was completed without the full multimodal engine.",
        "visual_insight":        None,
        "strengths":             [],
        "improvements":          [],
        "emotion_summary":       None,
        "emotion_stats":         doc.get("emotion_stats", {}),
        "per_question": [
            {
                "question": qa.get("question_text", ""),
                "score":    qa.get("llm_score"),
                "feedback": qa.get("llm_feedback", ""),
            }
            for qa in qas
        ],
    }
